"""
Django settings for dsr_api project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8w3t1r@%7blo39ws4zkp+wx%zqqel1sl%1+^-q98!8uwir0*f2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
if DEBUG:
    ALLOWED_HOSTS = ['*']


# Application definition

AUTH_USER_MODEL = "users.User"

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',

    'users.apps.UsersConfig',
    'groups.apps.GroupsConfig',
    'company.apps.CompanyConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
  'DEFAULT_AUTHENTICATION_CLASSES': (
    'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
    'users.backends.JWTAuthentication',
  ),
}

ROOT_URLCONF = 'dsr_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dsr_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'dsr',
        'USER': 'daniel',
        'PASSWORD': 'Moody123',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'


# Group fields
DSR_ADMIN_GROUP_NAME = 'DSR Admin'
DSR_ADMIN_SLUG_FIELD = 'dsr-admin'

DSR_EMPLOYEE_GROUP_NAME = 'DSR Employee'
DSR_EMPLOYEE_SLUG_FIELD = 'dsr-employee'

DSR_CUSTOMER_SUPER_ADMIN_GROUP_NAME = 'DSR Customer Super Admin'
DSR_CUSTOMER_SUPER_ADMIN_SLUG_FIELD = 'dsr-customer-super-admin'

DSR_CUSTOMER_ADMIN_GROUP_NAME = 'DSR Customer Admin'
DSR_CUSTOMER_ADMIN_SLUG_FIELD = 'dsr-customer-admin'

DSR_CUSTOMER_USER_GROUP_NAME = "DSR Customer User"
DSR_CUSTOMER_USER_SLUG_FIELD = 'dsr-customer-user'

# Custom permissions
# User
# DSR Admin
CAN_ADD_DSR_ADMIN_NAME = 'Can add DSR Admin'
CAN_ADD_DSR_ADMIN_PERM = 'can_add_dsr_admin'
CAN_ADD_DSR_ADMIN_PERM_NAME = 'users.can_add_dsr_admin'

CAN_DELETE_DSR_ADMIN_NAME = 'Can delete DSR Admin'
CAN_DELETE_DSR_ADMIN_PERM = 'can_delete_dsr_admin'
CAN_DELETE_DSR_ADMIN_PERM_NAME = 'users.can_delete_dsr_admin'

CAN_UPDATE_DSR_ADMIN_NAME = 'Can update DSR Admin'
CAN_UPDATE_DSR_ADMIN_PERM = 'can_update_dsr_admin'
CAN_UPDATE_DSR_ADMIN_PERM_NAME = 'users.can_update_dsr_admin'

# DSR Employee
CAN_ADD_DSR_EMPLOYEE_NAME = 'Can add DSR Employee'
CAN_ADD_DSR_EMPLOYEE_PERM = 'can_add_dsr_employee'
CAN_ADD_DSR_EMPLOYEE_PERM_NAME = 'users.can_add_dsr_employee'

CAN_DELETE_DSR_EMPLOYEE_NAME = 'Can delete DSR Employee'
CAN_DELETE_DSR_EMPLOYEE_PERM = 'can_delete_dsr_employee'
CAN_DELETE_DSR_EMPLOYEE_PERM_NAME = 'users.can_delete_dsr_employee'

CAN_UPDATE_DSR_EMPLOYEE_NAME = 'Can update DSR Employee'
CAN_UPDATE_DSR_EMPLOYEE_PERM = 'can_update_dsr_employee'
CAN_UPDATE_DSR_EMPLOYEE_PERM_NAME = 'users.can_update_dsr_employee'

# DSR Customer Super Admin
CAN_ADD_DSR_CUSTOMER_SUPER_ADMIN_NAME = 'Can add DSR Customer Super Admin'
CAN_ADD_DSR_CUSTOMER_SUPER_ADMIN_PERM = 'can_add_dsr_customer_super_admin'
CAN_ADD_DSR_CUSTOMER_SUPER_ADMIN_PERM_NAME = 'users.can_add_dsr_customer_super_admin'

CAN_DELETE_DSR_CUSTOMER_SUPER_ADMIN_NAME = 'Can delete DSR Customer Super Admin'
CAN_DELETE_DSR_CUSTOMER_SUPER_ADMIN_PERM = '.can_delete_dsr_customer_super_admin'
CAN_DELETE_DSR_CUSTOMER_SUPER_ADMIN_PERM_NAME = 'users.can_delete_dsr_customer_super_admin'

CAN_UPDATE_DSR_CUSTOMER_SUPER_ADMIN_NAME = 'Can update DSR Customer Super Admin'
CAN_UPDATE_DSR_CUSTOMER_SUPER_ADMIN_PERM = 'can_update_dsr_customer_super_admin'
CAN_UPDATE_DSR_CUSTOMER_SUPER_ADMIN_PERM_NAME = 'users.can_update_dsr_customer_super_admin'

# DSR Customer Admin
CAN_ADD_DSR_CUSTOMER_ADMIN_NAME = 'Can add DSR Customer Admin'
CAN_ADD_DSR_CUSTOMER_ADMIN_PERM = 'can_add_dsr_customer_admin'
CAN_ADD_DSR_CUSTOMER_ADMIN_PERM_NAME = 'users.can_add_dsr_customer_admin'

CAN_DELETE_DSR_CUSTOMER_ADMIN_NAME = 'Can delete DSR Customer Admin'
CAN_DELETE_DSR_CUSTOMER_ADMIN_PERM = 'can_delete_dsr_customer_admin'
CAN_DELETE_DSR_CUSTOMER_ADMIN_PERM_NAME = 'users.can_delete_dsr_customer_admin'

CAN_UPDATE_DSR_CUSTOMER_ADMIN_NAME = 'Can update DSR Customer Admin'
CAN_UPDATE_DSR_CUSTOMER_ADMIN_PERM = 'can_update_dsr_customer_admin'
CAN_UPDATE_DSR_CUSTOMER_ADMIN_PERM_NAME = 'users.can_update_dsr_customer_admin'

# DSR Customer User
CAN_ADD_DSR_CUSTOMER_USER_NAME = 'Can add DSR Customer User'
CAN_ADD_DSR_CUSTOMER_USER_PERM = 'can_add_dsr_customer_user'
CAN_ADD_DSR_CUSTOMER_USER_PERM_NAME = 'users.can_add_dsr_customer_user'

CAN_DELETE_DSR_CUSTOMER_USER_NAME = 'Can delete DSR Customer User'
CAN_DELETE_DSR_CUSTOMER_USER_PERM = 'can_delete_dsr_customer_user'
CAN_DELETE_DSR_CUSTOMER_USER_PERM_NAME = 'users.can_delete_dsr_customer_user'

CAN_UPDATE_DSR_CUSTOMER_USER_NAME = 'Can update DSR Customer User'
CAN_UPDATE_DSR_CUSTOMER_USER_PERM = 'can_update_dsr_customer_user'
CAN_UPDATE_DSR_CUSTOMER_USER_PERM_NAME = 'users.can_update_dsr_customer_user'

# Company
CAN_ADD_COMPANY_PERM_NAME = 'company.add_company'
CAN_CHANGE_COMPANY_PERM_NAME = 'company.change_company'
CAN_VIEW_COMPANY_PERM_NAME = 'company.view_company'
CAN_DELETE_COMPANY_PERM_NAME = 'company.delete_company'
