# Generated by Django 2.1.5 on 2019-01-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug_field', models.SlugField(max_length=100)),
                ('image_url', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
